# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagicTheGatheringDatabase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagicTheGatheringDatabase
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'
  pod 'SnapKit', '~> 3.2.0'
  pod 'PagedArray', '~> 0.6'
  target 'MagicTheGatheringDatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MagicTheGatheringDatabaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
